// <auto-generated />
namespace AdamPersonalCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedboolforowned : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedboolforowned));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041723252_addedboolforowned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
