// <auto-generated />
namespace AdamPersonalCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class hadissuesdeletedpriormigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hadissuesdeletedpriormigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202002051524460_hadissuesdeletedpriormigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
